export default function () {
	return [
		{ id: 1, name: 'Windows SDK', type: 'JavaScript Framework' },
    { id: 2, name: 'C++', type: 'JavaScript Framework' },
    { id: 3, name: 'VC++', type: 'Development Language' },
    { id: 4, name: 'C#', type: 'PHP Framework' },
    { id: 5, name: '.NET', type: 'PHP Framework' },
    { id: 6, name: 'COM', type: 'Database' },
    { id: 7, name: 'ATL', type: 'Database' },
    { id: 8, name: 'UML', type: 'Database' },
		{ id: 1, name: 'RUP', type: 'JavaScript Framework' },
    { id: 2, name: 'SQL Server', type: 'JavaScript Framework' },
		{ id: 4, name: 'Analysis Services', type: 'PHP Framework' },
		{ id: 5, name: 'OLAP', type: 'PHP Framework' },
		{ id: 6, name: 'Drupal', type: 'Database' },
		{ id: 7, name: 'Heroku', type: 'Database' },
		{ id: 8, name: 'Objective-C', type: 'Database' },
		{ id: 4, name: 'Qt', type: 'PHP Framework' },
    { id: 5, name: 'X-Code', type: 'PHP Framework' },
    { id: 6, name: 'S3', type: 'Database' },
    { id: 7, name: 'EC2', type: 'Database' },
    { id: 8, name: 'EBS', type: 'Database' },
		{ id: 3, name: 'Java', type: 'Development Language' },
		{ id: 4, name: 'ATG Dynamo', type: 'PHP Framework' },
    { id: 5, name: 'BEA Weblogic', type: 'PHP Framework' },
    { id: 6, name: 'Flash', type: 'Database' },
    { id: 7, name: 'ActionScript', type: 'Database' },
    { id: 8, name: 'Flex', type: 'Database' },
    { id: 4, name: 'Jenkins', type: 'PHP Framework' },
    { id: 5, name: 'Subversion', type: 'PHP Framework' },
    { id: 6, name: 'Agile', type: 'Database' },
    { id: 7, name: 'Bugzilla', type: 'Database' },
    { id: 8, name: 'Jira', type: 'Database' },
		{ id: 1, name: 'Caringorm', type: 'JavaScript Framework' },
    { id: 2, name: 'RobotLegs', type: 'JavaScript Framework' },
    { id: 3, name: 'PureMVC', type: 'Development Language' },
    { id: 4, name: 'Ruby on Rails', type: 'PHP Framework' },
    { id: 5, name: 'xPath', type: 'PHP Framework' },
    { id: 6, name: 'XSLT', type: 'Database' },
    { id: 7, name: 'XML', type: 'Database' },
    { id: 8, name: 'Oracle', type: 'Database' },
		{ id: 1, name: 'Pentaho', type: 'JavaScript Framework' },
    { id: 2, name: 'PHP', type: 'JavaScript Framework' },
    { id: 3, name: 'Zend', type: 'Development Language' },
    { id: 4, name: 'PostgreSQL', type: 'PHP Framework' },
    { id: 5, name: 'Symfony', type: 'PHP Framework' },
    { id: 6, name: 'Angular2', type: 'Database' },
    { id: 7, name: 'Laravel', type: 'Database' },
    { id: 8, name: 'AngularJS', type: 'Database' }
  ]
}
