export default function () {
	return [
    { id: 2, name: 'C++', type: 'Development Language' },
		{ id: 4, name: 'Qt', type: 'C++ Framework' },
		{ id: 4, name: 'Visual Studio', type: 'Devlopment Environment' },
    { id: 4, name: 'C#', type: 'Development Language' },
    { id: 5, name: '.NET', type: 'Development Framework' },
    { id: 8, name: 'UML', type: 'Database' },
		{ id: 1, name: 'RUP', type: 'Development Process' },
    { id: 2, name: 'SQL Server', type: 'Database' },
		{ id: 5, name: 'OLAP', type: 'PHP Framework' },
		{ id: 8, name: 'Objective-C', type: 'Development Language' },
    { id: 5, name: 'Xcode', type: 'Devlopment Environment' },
		{ id: 3, name: 'Java', type: 'Development Language' },
		{ id: 4, name: 'ATG Dynamo', type: 'E-Commerce Framework' },
		{ id: 5, name: 'Oracle', type: 'Database' },
		{ id: 3, name: 'JMeter', type: 'Development Language' },
    { id: 6, name: 'Flash', type: 'Database' },
    { id: 7, name: 'ActionScript', type: 'Development Language' },
    { id: 8, name: 'Flex', type: 'Flash Framework' },
    { id: 5, name: 'Subversion', type: 'Source Control' },
    { id: 6, name: 'Agile', type: 'Development Process' },
    { id: 7, name: 'Bugzilla', type: 'Bug Traker' },
		{ id: 1, name: 'Caringorm', type: 'Flex Framework' },
    { id: 2, name: 'RobotLegs', type: 'Flex Framework' },
    { id: 3, name: 'PureMVC', type: 'Flex Framework' },
    { id: 4, name: 'Ruby on Rails', type: 'Development Language' },
    { id: 7, name: 'XML', type: 'Database' },
		{ id: 6, name: 'XSLT', type: 'Database' },
		{ id: 1, name: 'Pentaho', type: 'Database Reporting' },
    { id: 2, name: 'PHP', type: 'Development Language' },
    { id: 3, name: 'Zend', type: 'PHP Framework' },
		{ id: 6, name: 'Drupal', type: 'Database' },
		{ id: 4, name: 'PostgreSQL', type: 'PHP Framework' },
		{ id: 6, name: 'Ember', type: 'JavaScript Framework' },
    { id: 7, name: 'Knockout', type: 'JavaScript Framework' },
		{ id: 6, name: 'S3', type: 'AWS Service' },
		{ id: 5, name: 'Route53', type: 'AWS Service' },
    { id: 7, name: 'EC2', type: 'AWS Service' },
    { id: 8, name: 'EBS', type: 'AWS Service' },
		{ id: 8, name: 'RDS', type: 'Database' },
		{ id: 1, name: 'Less', type: 'JavaScript Framework' },
		{ id: 8, name: 'Jira', type: 'Task Management' },
		{ id: 4, name: 'Jenkins', type: 'Continous' },
		{ id: 8, name: 'Angular', type: 'JavaScript Framework' },
		{ id: 7, name: 'Laravel', type: 'PHP Framework' },
		{ id: 6, name: 'Cordova', type: 'Database' },
		{ id: 5, name: 'Symfony', type: 'PHP Framework' },
		{ id: 7, name: 'Heroku', type: 'Hosting Provider' }
  ]
}
