export default function () {
	return [
		{ id: 1, name: 'C++', type: 'Development Language' },
		{ id: 2, name: 'Visual Studio', type: 'Devlopment Environment' },
		{ id: 3, name: 'C#', type: 'Development Language' },
		{ id: 4, name: '.NET', type: 'Development Framework' },
		{ id: 5, name: 'SQL Server', type: 'Database' },
		{ id: 6, name: 'OLAP', type: 'Multidimensional Analysis' },
		{ id: 7, name: 'Objective-C', type: 'Development Language' },
		{ id: 8, name: 'PHP', type: 'Development Language' },
		{ id: 9, name: 'Zend', type: 'PHP Framework' },
		{ id: 10, name: 'Java', type: 'Development Language' },
		{ id: 11, name: 'Heroku', type: 'Hosting Provider' },
		{ id: 12, name: 'Ruby on Rails', type: 'Development Language' },
		{ id: 13, name: 'Flash', type: 'Animation Tool' },
		{ id: 14, name: 'ActionScript', type: 'Development Language' },
		{ id: 15, name: 'Flex', type: 'Flash Framework' },
		{ id: 16, name: 'RobotLegs', type: 'Flex Framework' },
		{ id: 17, name: 'PureMVC', type: 'Flex Framework' },
		{ id: 18, name: 'PostgreSQL', type: 'Database' },
		{ id: 19, name: 'Drupal', type: 'Web Development Platform' },
		{ id: 20, name: 'XML', type: 'Markup Language' },
		{ id: 21, name: 'XSLT', type: 'XML Transformer' },
		{ id: 22, name: 'Oracle', type: 'Database' },
		{ id: 23, name: 'Pentaho', type: 'Database Reporting' },
		{ id: 24, name: 'Angular', type: 'JavaScript Framework' },
		{ id: 25, name: 'Laravel', type: 'PHP Framework' },
		{ id: 26, name: 'Cordova', type: 'Development Framework' },
		{ id: 27, name: 'Symfony', type: 'PHP Framework' },
		{ id: 28, name: 'Ember', type: 'JavaScript Framework' }
	]
}
